services:
  - type: web
    name: kucun
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kucun-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: kucun-db
    databaseName: kucun
    user: kucun
    plan: free
